package ReverseApp;


/**
* ReverseApp/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Tuesday, 9 March, 2021 11:02:58 AM IST
*/

public interface ReverseOperations 
{
  String reverseString (String str);
} // interface ReverseOperations
